#FROM Instruction
#The FROM instruction initializes a new build stage and sets 
#the Base Image for subsequent instructions. 
FROM ubuntu:22.04
RUN apt update -y
RUN apt install net-tools
CMD ["echo", "Hello from DIoT-2022"]