version: '3.8'
services:
  mqttbroker:  #service name
    build: .      #current directy 
    # image: eclipse-mosquitto   to pull any image directly from remote
    hostname: mosquitto_c   
    container_name: mqc
    networks:
      - default 
    expose:
      - 1883
    ports:
      - 6800:1883
  mqttpub:   #another service
    build: ./publisher_data #
    hostname: mosquitto_p
    container_name: mq_publisher
    networks:
      - default
    command: python3 mqtt_publish.py
    depends_on:  #depends on tells us to which service to run first
      - mqttbroker
      - mqttsub

  mqttsub:
    
    build: ./subscriber #
    hostname: mosquitto_s
    container_name: mq_subscriber
    networks:
      - default
    depends_on:
      - mqttbroker
    
    